// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devim/protobuf/page.proto

package page // import "github.com/devimteam/proto-utils/src/main/go/page"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order_Direction int32

const (
	Order_ASC  Order_Direction = 0
	Order_DESC Order_Direction = 1
)

var Order_Direction_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var Order_Direction_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x Order_Direction) String() string {
	return proto.EnumName(Order_Direction_name, int32(x))
}
func (Order_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_page_de224ea52ac4f902, []int{2, 0}
}

type Page struct {
	TotalPages           uint32   `protobuf:"varint,1,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalSize            uint64   `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_page_de224ea52ac4f902, []int{0}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetTotalPages() uint32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Page) GetTotalSize() uint64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *Page) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Page) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Sort struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_page_de224ea52ac4f902, []int{1}
}
func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (dst *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(dst, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type Order struct {
	Column               string          `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Direction            Order_Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=devim.protobuf.Order_Direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_page_de224ea52ac4f902, []int{2}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Order) GetDirection() Order_Direction {
	if m != nil {
		return m.Direction
	}
	return Order_ASC
}

type PageRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 *Sort    `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_page_de224ea52ac4f902, []int{3}
}
func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (dst *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(dst, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PageRequest) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func init() {
	proto.RegisterType((*Page)(nil), "devim.protobuf.Page")
	proto.RegisterType((*Sort)(nil), "devim.protobuf.Sort")
	proto.RegisterType((*Order)(nil), "devim.protobuf.Order")
	proto.RegisterType((*PageRequest)(nil), "devim.protobuf.PageRequest")
	proto.RegisterEnum("devim.protobuf.Order_Direction", Order_Direction_name, Order_Direction_value)
}

func init() { proto.RegisterFile("devim/protobuf/page.proto", fileDescriptor_page_de224ea52ac4f902) }

var fileDescriptor_page_de224ea52ac4f902 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4e, 0xe3, 0x40,
	0x10, 0xc6, 0x6f, 0x6d, 0x5f, 0xee, 0x3c, 0xd6, 0x45, 0xd1, 0xea, 0x40, 0xa1, 0x08, 0x89, 0x5c,
	0xb9, 0x89, 0x2d, 0x82, 0x28, 0x29, 0x48, 0x82, 0x28, 0x28, 0xb0, 0x6c, 0x24, 0x24, 0x9a, 0xc8,
	0x71, 0x16, 0xb3, 0x92, 0xed, 0x0d, 0xde, 0x35, 0x88, 0x14, 0x88, 0x47, 0x41, 0x94, 0x3c, 0x21,
	0x25, 0xda, 0x21, 0x7f, 0x44, 0x94, 0x6e, 0xe7, 0x9b, 0xdf, 0xcc, 0x7c, 0x33, 0x0b, 0x07, 0x33,
	0xf6, 0xc8, 0x8b, 0x60, 0x5e, 0x09, 0x25, 0xa6, 0xf5, 0x5d, 0x30, 0x4f, 0x32, 0xe6, 0x63, 0x44,
	0x9b, 0x98, 0xf2, 0x57, 0x29, 0xb7, 0x04, 0x2b, 0x4c, 0x32, 0x46, 0xbb, 0xe0, 0x28, 0xa1, 0x92,
	0x7c, 0xa2, 0x59, 0xd9, 0x26, 0x3d, 0xe2, 0xfd, 0x8b, 0x00, 0x25, 0x9d, 0x97, 0xb4, 0x03, 0xdf,
	0xd1, 0x44, 0xf2, 0x05, 0x6b, 0x1b, 0x3d, 0xe2, 0x59, 0x91, 0x8d, 0x4a, 0xcc, 0x17, 0x8c, 0x52,
	0xb0, 0x74, 0x65, 0xdb, 0xc2, 0x42, 0x7c, 0x6b, 0x0d, 0x61, 0x13, 0x61, 0x7c, 0xbb, 0x27, 0x60,
	0xc5, 0xa2, 0x52, 0xb4, 0x0f, 0x0d, 0x51, 0xcd, 0x58, 0xa5, 0x47, 0x99, 0x9e, 0x33, 0xd8, 0xf3,
	0x7f, 0x1a, 0xf3, 0xaf, 0x74, 0x36, 0x5a, 0x42, 0xee, 0x0b, 0xfc, 0x46, 0x81, 0xee, 0x43, 0x23,
	0x15, 0x79, 0x5d, 0x94, 0x68, 0xd1, 0x8e, 0x96, 0x11, 0x3d, 0x05, 0x7b, 0xc6, 0x2b, 0x96, 0x2a,
	0x2e, 0x4a, 0x74, 0xd7, 0x1c, 0x74, 0x77, 0xb6, 0xf4, 0xc7, 0x2b, 0x2c, 0xda, 0x54, 0xb8, 0x87,
	0x60, 0xaf, 0x75, 0xfa, 0x07, 0xcc, 0xb3, 0x78, 0xd4, 0xfa, 0x45, 0xff, 0x82, 0x35, 0x3e, 0x8f,
	0x47, 0x2d, 0xe2, 0x4e, 0xc0, 0xd1, 0x67, 0x88, 0xd8, 0x43, 0xcd, 0xa4, 0x5a, 0x6f, 0x4b, 0x76,
	0x6c, 0x6b, 0x6c, 0xb6, 0xa5, 0x1e, 0x58, 0x52, 0x54, 0x0a, 0x2f, 0xe0, 0x0c, 0xfe, 0x6f, 0x1b,
	0xd2, 0x97, 0x88, 0x90, 0x18, 0xbe, 0x12, 0xa0, 0xa9, 0x28, 0xb6, 0x88, 0xa1, 0xad, 0xa7, 0x86,
	0x3a, 0x0a, 0xc9, 0xed, 0x51, 0xc6, 0xd5, 0x7d, 0x3d, 0xf5, 0x53, 0x51, 0x04, 0xc8, 0x29, 0x96,
	0x2c, 0x7f, 0xb9, 0x5f, 0x2b, 0x9e, 0xcb, 0x40, 0x56, 0x69, 0x50, 0x24, 0xbc, 0x0c, 0x32, 0x81,
	0x9f, 0xfe, 0x46, 0xc8, 0x27, 0x21, 0xef, 0x86, 0x79, 0x11, 0x0e, 0x3f, 0x8c, 0xce, 0x18, 0x9b,
	0x87, 0xab, 0xf1, 0x37, 0x2c, 0xcf, 0x2f, 0x4b, 0xf1, 0x54, 0x5e, 0x3f, 0xcf, 0x99, 0x9c, 0x36,
	0xb0, 0xd3, 0xf1, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xac, 0x49, 0xd1, 0x3e, 0x02, 0x00,
	0x00,
}
