// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devim/protobuf/relay.proto

package relay // import "github.com/devimteam/proto-utils/src/main/go/relay"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import page "github.com/devimteam/proto-utils/src/main/go/page"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cursor struct {
	Before               *wrappers.StringValue `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After                *wrappers.StringValue `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	First                *wrappers.UInt32Value `protobuf:"bytes,3,opt,name=first,proto3" json:"first,omitempty"`
	Last                 *wrappers.UInt32Value `protobuf:"bytes,4,opt,name=last,proto3" json:"last,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_ee3553c4907c8c7d, []int{0}
}
func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (dst *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(dst, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

func (m *Cursor) GetBefore() *wrappers.StringValue {
	if m != nil {
		return m.Before
	}
	return nil
}

func (m *Cursor) GetAfter() *wrappers.StringValue {
	if m != nil {
		return m.After
	}
	return nil
}

func (m *Cursor) GetFirst() *wrappers.UInt32Value {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *Cursor) GetLast() *wrappers.UInt32Value {
	if m != nil {
		return m.Last
	}
	return nil
}

type Page struct {
	HasNextPage          bool                  `protobuf:"varint,1,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage      bool                  `protobuf:"varint,2,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	Start                *wrappers.StringValue `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  *wrappers.StringValue `protobuf:"bytes,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_ee3553c4907c8c7d, []int{1}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetHasNextPage() bool {
	if m != nil {
		return m.HasNextPage
	}
	return false
}

func (m *Page) GetHasPreviousPage() bool {
	if m != nil {
		return m.HasPreviousPage
	}
	return false
}

func (m *Page) GetStart() *wrappers.StringValue {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Page) GetEnd() *wrappers.StringValue {
	if m != nil {
		return m.End
	}
	return nil
}

type PageRequest struct {
	Cursor               *Cursor    `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Sort                 *page.Sort `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_ee3553c4907c8c7d, []int{2}
}
func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (dst *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(dst, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func (m *PageRequest) GetSort() *page.Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func init() {
	proto.RegisterType((*Cursor)(nil), "devim.protobuf.relay.Cursor")
	proto.RegisterType((*Page)(nil), "devim.protobuf.relay.Page")
	proto.RegisterType((*PageRequest)(nil), "devim.protobuf.relay.PageRequest")
}

func init() { proto.RegisterFile("devim/protobuf/relay.proto", fileDescriptor_relay_ee3553c4907c8c7d) }

var fileDescriptor_relay_ee3553c4907c8c7d = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x86, 0x19, 0x59, 0x36, 0x65, 0x4c, 0x29, 0x1d, 0xbc, 0x50, 0x4d, 0x5b, 0x8a, 0x56, 0xa6,
	0x50, 0xa9, 0xc8, 0x7d, 0x02, 0x37, 0x10, 0x42, 0x20, 0x08, 0x39, 0x17, 0xc8, 0xc6, 0x8c, 0xe4,
	0xa3, 0x0b, 0x48, 0x1a, 0x65, 0x66, 0xe4, 0xcb, 0x36, 0x4f, 0x12, 0xb2, 0xcc, 0x23, 0xe4, 0x49,
	0xf2, 0x28, 0x59, 0x86, 0x19, 0xc9, 0x71, 0x62, 0x62, 0xf0, 0x72, 0xe6, 0x7c, 0xff, 0x7f, 0xce,
	0xe1, 0x3f, 0x78, 0x38, 0x87, 0x45, 0x56, 0xb8, 0x15, 0x67, 0x92, 0x85, 0x75, 0xec, 0x72, 0xc8,
	0xe9, 0xda, 0xd1, 0x4f, 0x32, 0xd0, 0x35, 0x67, 0x53, 0x73, 0x74, 0x6d, 0xf8, 0x33, 0x61, 0x2c,
	0xc9, 0x61, 0x2b, 0x59, 0x72, 0x5a, 0x55, 0xc0, 0x45, 0x03, 0x0e, 0xbf, 0xed, 0x38, 0x56, 0x34,
	0x81, 0xa6, 0x64, 0x3f, 0x21, 0xdc, 0xfb, 0x5f, 0x73, 0xc1, 0x38, 0xf9, 0x87, 0x7b, 0x21, 0xc4,
	0x8c, 0x83, 0x85, 0x7e, 0xa1, 0x51, 0xdf, 0xfb, 0xee, 0x34, 0xb6, 0xdb, 0x6e, 0x53, 0xc9, 0xb3,
	0x32, 0xb9, 0xa4, 0x79, 0x0d, 0x41, 0xcb, 0x12, 0x0f, 0x77, 0x69, 0x2c, 0x81, 0x5b, 0xc6, 0x01,
	0xa2, 0x06, 0x55, 0x9a, 0x38, 0xe3, 0x42, 0x5a, 0x9d, 0x3d, 0x9a, 0x8b, 0x93, 0x52, 0x8e, 0xbd,
	0x56, 0xa3, 0x51, 0xf2, 0x17, 0x9b, 0x39, 0x15, 0xd2, 0x32, 0x0f, 0x90, 0x68, 0xd2, 0x7e, 0x44,
	0xd8, 0xf4, 0x69, 0x02, 0xc4, 0xc6, 0x9f, 0x53, 0x2a, 0x66, 0x25, 0xac, 0xe4, 0x4c, 0xad, 0xae,
	0xf7, 0xfb, 0x14, 0xf4, 0x53, 0x2a, 0xce, 0x60, 0x25, 0x35, 0xf3, 0x1b, 0x7f, 0x55, 0x4c, 0xc5,
	0x61, 0x91, 0xb1, 0x5a, 0x34, 0x9c, 0xa1, 0xb9, 0x2f, 0x29, 0x15, 0x7e, 0xfb, 0xaf, 0x59, 0x0f,
	0x77, 0x85, 0xa4, 0x7c, 0xff, 0xf8, 0xef, 0x56, 0xd6, 0x28, 0x71, 0x70, 0x07, 0xca, 0xf9, 0xde,
	0xe9, 0xdf, 0x2a, 0x14, 0x68, 0x17, 0xb8, 0xaf, 0x7a, 0x05, 0x70, 0x53, 0x83, 0x90, 0x2a, 0x9b,
	0x48, 0xa7, 0xf4, 0x9a, 0xcd, 0x47, 0x87, 0xe0, 0x34, 0x49, 0x06, 0x2d, 0x4b, 0x46, 0xd8, 0x14,
	0x8c, 0xcb, 0x36, 0x9a, 0xc1, 0xae, 0x66, 0xca, 0xb8, 0x0c, 0x34, 0x31, 0xb9, 0x45, 0x98, 0x44,
	0xac, 0xd8, 0x21, 0x26, 0x38, 0x50, 0xb6, 0xbe, 0x7a, 0xfa, 0xe8, 0xda, 0x4b, 0x32, 0x99, 0xd6,
	0xa1, 0x13, 0xb1, 0xc2, 0xd5, 0xa0, 0x04, 0xda, 0x5e, 0xd5, 0x9f, 0x5a, 0x66, 0xb9, 0x70, 0x05,
	0x8f, 0xdc, 0x82, 0x66, 0xa5, 0x9b, 0xb0, 0xe6, 0x6c, 0xef, 0x10, 0x7a, 0x46, 0xe8, 0xde, 0xe8,
	0x1c, 0xfb, 0x93, 0x07, 0xe3, 0xc7, 0x91, 0xb6, 0xf7, 0x37, 0x03, 0x5c, 0x41, 0x9e, 0x9f, 0x96,
	0x6c, 0x59, 0x9e, 0xaf, 0x2b, 0x10, 0x61, 0x4f, 0x5b, 0x8d, 0x5f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xad, 0xff, 0xa2, 0x10, 0x01, 0x03, 0x00, 0x00,
}
