// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devim/protobuf/collect.proto

package collect // import "github.com/devimteam/proto-utils/src/main/go/collect"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UInt32Range struct {
	Start                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UInt32Range) Reset()         { *m = UInt32Range{} }
func (m *UInt32Range) String() string { return proto.CompactTextString(m) }
func (*UInt32Range) ProtoMessage()    {}
func (*UInt32Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_collect_39b82a0c0c46bfd0, []int{0}
}
func (m *UInt32Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt32Range.Unmarshal(m, b)
}
func (m *UInt32Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt32Range.Marshal(b, m, deterministic)
}
func (dst *UInt32Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt32Range.Merge(dst, src)
}
func (m *UInt32Range) XXX_Size() int {
	return xxx_messageInfo_UInt32Range.Size(m)
}
func (m *UInt32Range) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt32Range.DiscardUnknown(m)
}

var xxx_messageInfo_UInt32Range proto.InternalMessageInfo

func (m *UInt32Range) GetStart() *wrappers.UInt32Value {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *UInt32Range) GetEnd() *wrappers.UInt32Value {
	if m != nil {
		return m.End
	}
	return nil
}

type UInt64Range struct {
	Start                *wrappers.UInt64Value `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *wrappers.UInt64Value `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UInt64Range) Reset()         { *m = UInt64Range{} }
func (m *UInt64Range) String() string { return proto.CompactTextString(m) }
func (*UInt64Range) ProtoMessage()    {}
func (*UInt64Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_collect_39b82a0c0c46bfd0, []int{1}
}
func (m *UInt64Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UInt64Range.Unmarshal(m, b)
}
func (m *UInt64Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UInt64Range.Marshal(b, m, deterministic)
}
func (dst *UInt64Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UInt64Range.Merge(dst, src)
}
func (m *UInt64Range) XXX_Size() int {
	return xxx_messageInfo_UInt64Range.Size(m)
}
func (m *UInt64Range) XXX_DiscardUnknown() {
	xxx_messageInfo_UInt64Range.DiscardUnknown(m)
}

var xxx_messageInfo_UInt64Range proto.InternalMessageInfo

func (m *UInt64Range) GetStart() *wrappers.UInt64Value {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *UInt64Range) GetEnd() *wrappers.UInt64Value {
	if m != nil {
		return m.End
	}
	return nil
}

func init() {
	proto.RegisterType((*UInt32Range)(nil), "devim.protobuf.UInt32Range")
	proto.RegisterType((*UInt64Range)(nil), "devim.protobuf.UInt64Range")
}

func init() {
	proto.RegisterFile("devim/protobuf/collect.proto", fileDescriptor_collect_39b82a0c0c46bfd0)
}

var fileDescriptor_collect_39b82a0c0c46bfd0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x49, 0x2d, 0xcb,
	0xcc, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0xce, 0xcf, 0xc9, 0x49,
	0x4d, 0x2e, 0xd1, 0x03, 0x0b, 0x08, 0xf1, 0x81, 0x65, 0xf5, 0x60, 0xb2, 0x52, 0x72, 0xe9, 0xf9,
	0xf9, 0xe9, 0x39, 0xa9, 0x08, 0xe5, 0xe5, 0x45, 0x89, 0x05, 0x05, 0xa9, 0x45, 0xc5, 0x10, 0x25,
	0x4a, 0x85, 0x5c, 0xdc, 0xa1, 0x9e, 0x79, 0x25, 0xc6, 0x46, 0x41, 0x89, 0x79, 0xe9, 0xa9, 0x42,
	0x46, 0x5c, 0xac, 0xc5, 0x25, 0x89, 0x45, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x32,
	0x7a, 0x10, 0xed, 0x70, 0xf3, 0xf4, 0x20, 0x8a, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x83, 0x20, 0x4a,
	0x85, 0xf4, 0xb8, 0x98, 0x53, 0xf3, 0x52, 0x24, 0x98, 0x88, 0xd0, 0x01, 0x52, 0x08, 0xb3, 0xd2,
	0xcc, 0x84, 0x04, 0x2b, 0xcd, 0x4c, 0x48, 0xb5, 0x12, 0xa6, 0x03, 0xa4, 0xd0, 0xa9, 0x8d, 0x91,
	0x4b, 0x28, 0x39, 0x3f, 0x57, 0x0f, 0x35, 0x70, 0x9c, 0x78, 0x9c, 0x21, 0x61, 0x17, 0x00, 0x12,
	0x08, 0x60, 0x8c, 0x32, 0x49, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x07,
	0x2b, 0x2d, 0x49, 0x4d, 0x84, 0x86, 0xb4, 0x6e, 0x69, 0x49, 0x66, 0x4e, 0xb1, 0x7e, 0x71, 0x51,
	0xb2, 0x7e, 0x6e, 0x62, 0x66, 0x9e, 0x7e, 0x7a, 0x3e, 0x2c, 0xe0, 0x17, 0x30, 0x32, 0xfe, 0x60,
	0x64, 0x5c, 0xc4, 0xc4, 0xec, 0x1e, 0xe0, 0xb4, 0x8a, 0x49, 0xd6, 0x05, 0x6c, 0x45, 0x00, 0xcc,
	0x29, 0xe1, 0xa9, 0x39, 0x39, 0xde, 0x79, 0xf9, 0xe5, 0x79, 0x21, 0x95, 0x05, 0xa9, 0xc5, 0x49,
	0x6c, 0x60, 0xc3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x7c, 0x42, 0x27, 0xc5, 0x01,
	0x00, 0x00,
}
